// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'music_handler.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `calc_fingerprint`, `get_duration`, `lookup_metadata`, `lookup_rs`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AcoustIdArtist`, `AcoustIdRecording`, `AcoustIdReleaseGroup`, `AcoustIdResponse`, `AcoustIdResult`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<SongMetadata?> lookup({required String path}) =>
    RustLib.instance.api.crateApiAcoustidLookup(path: path);
