// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'plugin_man.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `read_plugin_metadata`, `rpc_config_to_plugin_config`, `validate_rpc_config`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AdiPluginMan`, `PluginManErr`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `load_plugin_with_metadata`, `new`, `remove_plugin`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Mutex < Plugin > >>>
abstract class ArcMutexPlugin implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PluginInode>>
abstract class PluginInode implements RustOpaqueInterface {
  Map<String, ConfigTypes> get config;

  ArcMutexPlugin get plugin;

  set config(Map<String, ConfigTypes> config);

  set plugin(ArcMutexPlugin plugin);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RpcConfig>>
abstract class RpcConfig implements RustOpaqueInterface {
  String get ctype;

  Value get defaultVal;

  String get key;

  set ctype(String ctype);

  set defaultVal(Value defaultVal);

  set key(String key);
}

@freezed
sealed class ConfigTypes with _$ConfigTypes {
  const ConfigTypes._();

  const factory ConfigTypes.string(
    String field0,
  ) = ConfigTypes_String;
  const factory ConfigTypes.bool(
    bool field0,
  ) = ConfigTypes_Bool;
  const factory ConfigTypes.int(
    int field0,
  ) = ConfigTypes_Int;
  const factory ConfigTypes.uInt(
    int field0,
  ) = ConfigTypes_UInt;
  const factory ConfigTypes.bigInt(
    BigInt field0,
  ) = ConfigTypes_BigInt;
  const factory ConfigTypes.bigUInt(
    BigInt field0,
  ) = ConfigTypes_BigUInt;
}
