// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `download_file`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `check_dir`, `fpre`, `validate_path`

Future<bool> checkUnsafeApi() =>
    RustLib.instance.api.crateApiUtilsCheckUnsafeApi();

Future<bool> checkPluginsEnabled() =>
    RustLib.instance.api.crateApiUtilsCheckPluginsEnabled();

Future<String?> getLatestVersion() =>
    RustLib.instance.api.crateApiUtilsGetLatestVersion();

Future<bool> updateExecutable({required String arch, required String expath}) =>
    RustLib.instance.api
        .crateApiUtilsUpdateExecutable(arch: arch, expath: expath);
